FROM python:3.10-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем клиентские сертификаты
COPY client-creds /app/client-creds

# Копируем скрипт
COPY producer.py consumer.py ./

CMD ["python", "producer.py"]